name: build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# SARIF 업로드용 권한(Trivy 결과를 Security 탭에 올릴 때 필요)
permissions:
  contents: read
  security-events: write

jobs:
  # --- Part 1: Static Code Scan (Trivy, repo mode) ---
  sast_scan:
    name: Run SAST Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL

      # (선택) Security → Code scanning alerts에 바로 표시
      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          category: trivy

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-results.sarif

  # --- Part 2: Docker Scout Image Scan ---
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1
        with:
          docker_version: '20.10.7'

      - name: Build Docker Image
        run: docker build -f Dockerfile -t pygoat_app:latest .

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.15.0
        with:
          dockerhub-user: ${{ secrets.REPO_USER }}   # ex) hyungjunchoi1
          dockerhub-password: ${{ secrets.REPO_PWD }}# ex) dckr_pat_...
          command: quickview,cves
          only-severities: critical,high
          sarif-file: scout-report.sarif

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: docker-scout-findings
          path: scout-report.sarif
